const types = {
  config: {
    LANG: 'LANG',
    HOME: 'HOME',
    HOMETYPE: 'HOMETYPE',
    LAYOUT: 'LAYOUT',
    NAVTHEME: 'NAVTHEME',
    PRIMARYCOLOR: 'PRIMARYCOLOR',
    ACCORDION: 'ACCORDION',
    FIXEDHEADER: 'FIXEDHEADER',
    FIXSIDERBAR: 'FIXSIDERBAR',
    HEADERHEIGHT: 'HEADERHEIGHT',
    SIDERBARTHEME: 'SIDERBARTHEME',
    TOPBARTHEME: 'TOPBARTHEME',
    WEAK: 'WEAK',
    MULTITAB: 'MULTITAB',
  },
};

export default types;
